### ISSUE TITLE
The "new content available" flow is broken

### ISSUE THREAD

**Issue by NOtherDev** [kefranabg/bento-starter#132] opened 2019-04-26 20:08 UTC
**Describe the bug**
Updating the Service Worker when its new version is detected is tricky and complex and requires back-and-forth communication with the waiting worker, not just reloading the screen.

See [Updating the service worker](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates)

> Even if you only have one tab open to the demo, refreshing the page isn't enough to let the new version take over. This is due to how browser navigations work. When you navigate, the current page doesn't go away until the response headers have been received, and even then the current page may stay if the response has a Content-Disposition header. Because of this overlap, the current service worker is always controlling a client during a refresh.

**To Reproduce**
1. Install the app so that SW is installed
2. Change the SW to invoke "new content available" flow
3. Click the toast to reload (ensure no devtools open)
4. See that the previous Service Worker is still controlling the page, not the new one

**Expected behavior**
The new Service Worker should take over. The click on the toast should post the message to the waiting Service Worker instance and instruct it to `skipWaiting`. Then, `controllerchange` event should be observed and only then the page can be reloaded.

**Comment by kefranabg** [comment] 2019-04-26 21:06
Hi @NOtherDev 👋Thanks for this clean issue report 👍

What makes you say that the new service worker do not take over ?

I just tested and everything seems to be ok :confused:

Here are the steps I used to reproduce : 
- Run `npm run build && http-server ./dist/`
- Open browser on `localhost:8080`
- Open chrome devtools and go to `Application tab => Service Workers on the side menu => click on service-worker.js` and now I can see the active service worker sources
- Go to the `dist` folder and modify the `service-worker.js` file with a comment
- Stop the current `http-server` process
- Run `npm run build && http-server ./dist/` again
- Refresh my page on chrome
- Now I can see that the new service worker (with the comment I added) has immediately take the control

Let me know if this workflow works for you.

Here is the service worker workflow of bento-starter :

When a new version of the service worker is generated, next time a user load the application, the new service worker will immediately take over. However, static files are out of date, this is why the user need to refresh.

The `skipWaiting` option is actually used in the current service worker configuration (check the `/public/service-worker.js` file line 3)

If I'm missing something, please let me know ! 😄

**Comment by NOtherDev** [comment] 2019-04-26 22:21
Ah sorry, so there is no waiting phase for the newly installed Service Worker in this implementation.
Forceful `skipWaiting` [has its risks](https://stackoverflow.com/a/49494141/142827), though. I think the "full" flow with on-demand skipWaiting and deferred refresh is safer.

**Comment by kefranabg** [comment] 2019-04-27 07:28
Indeed there is risks if the user continue navigating without refreshing the old version. I should say that I like the on-demand skipWaiting flow you suggest though 👍 

I'll close this issue (as it's not a real one) and open a new one to improve the service worker workflow 😉

Thanks @NOtherDev that was helpful 🙏

**Closed by kefranabg** 2019-04-27 07:28 UTC
